spring:
  datasource:
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    usernaem: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enable: true